{{- if .Values.insights.enabled }}

{{- $tagsArray := .Values.insights.tags -}}
{{- $ddTagsCustomerProvided := "" -}}
{{- $orgId := "" -}}
{{- $serviceId := "" -}}
{{- $serviceName := "" -}}

{{- range $index, $tag := $tagsArray -}}
  {{- range $key, $value := $tag -}}
    {{- if eq $key "org_id" -}}
      {{- $orgId = $value -}}
    {{- end -}}
    {{- if eq $key "service_id" -}}
      {{- $serviceId = $value -}}
    {{- end -}}
    {{- if eq $key "service_name" -}}
      {{- $serviceName = $value -}}
    {{- end -}}
    {{- $ddTagsCustomerProvided = printf "%s%s%s:%s" $ddTagsCustomerProvided (ternary "" " " (eq $ddTagsCustomerProvided "")) $key $value -}}
  {{- end -}}
{{- end -}}

{{- if eq $orgId "" -}}
  {{- fail "Organization ID not specified" -}}
{{- end -}}

{{- if eq $serviceId "" -}}
  {{- $serviceId = (randAlpha 6) -}}
{{- end -}}
{{- if eq $serviceName "" -}}
  {{- $serviceName = printf "service_%s" $serviceId -}}
{{- end -}}


{{- $environmentName := .Values.insights.environment_name -}}
{{- $maasDatacenterId := printf "%s_%s" $orgId $environmentName -}}

{{- $serviceType := "standard" -}}
{{- if .Values.image.repository -}}
  {{- if contains "enterprise" .Values.image.repository -}}
    {{- $serviceType = "enterprise" -}}
  {{- else if contains "standard" .Values.image.repository -}}
    {{- $serviceType = "standard" -}}
  {{- end -}}
{{- end -}}

{{- $ddTagsCalculated := printf "infrastructure_name:%s-%s-%s maas_datacenter_id:%s service_class:%s maas_instance:%s-selfhosted-host service_type:%s" (include "solace.fullname" .) .Values.solace.size (randAlpha 4) $maasDatacenterId .Values.solace.size (include "solace.fullname" .) $serviceType -}}
{{- $ddTagsDefault := "monitoring_mode:advanced datacenter_access_type:Private datacenter_type:CustomerManaged is_trial:false peb_type:software provider:k8s maas_id:customermanaged " -}}

{{- $ddTags := printf "%s %s %s" $ddTagsDefault $ddTagsCalculated $ddTagsCustomerProvided -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "solace.fullname" . }}-agentv2-0
data:
  DD_HOSTNAME: "{{ template "solace.fullname" . }}-selfhosted-host"
  DD_SITE: {{ .Values.insights.datadogSite }}
  DD_TAGS: {{ printf "%s %s " $ddTags "ha_role:primary" }}

  {{- end}}
