{{- if .Values.solace.usernameAdminPasswordSecretName }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.solace.usernameAdminPasswordSecretName) }}
{{- if not $existingSecret }}
{{- fail (printf "Error: Secret '%s' not found in namespace '%s'. Please create the secret before deploying." .Values.solace.usernameAdminPasswordSecretName .Release.Namespace) }}
{{- end }}
{{- if not (index $existingSecret.data "username_admin_password") }}
{{- fail (printf "Error: Secret '%s' does not contain the required key 'username_admin_password'. Please ensure the secret has the required key." .Values.solace.usernameAdminPasswordSecretName) }}
{{- end }}
{{- else }}
{{- $secretBase := include "solace.fullname" . }}
{{- $secretName := printf "%s-%s" $secretBase "secrets" }}
{{- $adminPasswordValue := (randAlpha 10) | b64enc | quote }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- if $secret }}
{{- $adminPasswordValue = index $secret.data "username_admin_password" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/name: {{ template "solace.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
{{ if .Values.solace.usernameAdminPassword }}
  username_admin_password:  {{ .Values.solace.usernameAdminPassword | b64enc | quote }}
{{ else }}
  username_admin_password: {{ $adminPasswordValue}}
{{ end }}
{{- end }}

