{{- if .Values.solace.redundancy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "solace.fullname" . }}-discovery
  labels:
    {{- include "solace.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 8080
    name: tcp-semp
  - port: 8741
    name: tcp-ha-mate-link
  - port: 8300
    name: tcp-ha-conf-sync0
  - port: 8301
    name: tcp-ha-conf-sync1
  - port: 8302
    name: tcp-ha-conf-sync2
  clusterIP: None
  selector:
    {{- include "solace.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
{{- end }}
