# Load Service part of template
apiVersion: v1
kind: Service
metadata:
  name: {{ template "solace.fullname" . }}
  labels:
    {{- include "solace.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{.Values.service.type | default "LoadBalancer"}}
  {{- if .Values.insights.enabled }}
  publishNotReadyAddresses: true
  {{- end }}
  ports:
  {{- range $item := .Values.service.ports }}
  - port: {{ $item.servicePort }}
    targetPort: {{ $item.containerPort }}
    protocol: {{ $item.protocol }}
    name: {{ $item.name }}
  {{- end}}
  selector:
    {{- include "solace.selectorLabels" . | nindent 4 }}
    active: "true"
