apiVersion: v1
kind: Service
metadata:
  name: pod-modifier-webhook
  labels:
    app: solace-pod-modifier-webhook
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: solace-pod-modifier-webhook
