apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solace-pod-modifier
resources:
- namespace.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
images:
- name: pod-modifier
  newName: pod-modifier
